// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqamoRyCldLXpwqanAk7ctbXlTIwoWvNk',
    appId: '1:236726991923:web:8e27545e5e906023fff746',
    messagingSenderId: '236726991923',
    projectId: 'hybriidflow-96404',
    authDomain: 'hybriidflow-96404.firebaseapp.com',
    storageBucket: 'hybriidflow-96404.firebasestorage.app',
    measurementId: 'G-GM00T24ZNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB47Djrtc5xsIywwmLnV-990a4RohltLJ8',
    appId: '1:236726991923:android:7a93500b8bee250cfff746',
    messagingSenderId: '236726991923',
    projectId: 'hybriidflow-96404',
    storageBucket: 'hybriidflow-96404.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4mN6ZIGTi_Uu5xh6B_NPcRc4JjzPsDp0',
    appId: '1:236726991923:ios:ab36d556ee60f258fff746',
    messagingSenderId: '236726991923',
    projectId: 'hybriidflow-96404',
    storageBucket: 'hybriidflow-96404.firebasestorage.app',
    iosBundleId: 'com.example.hybriidflow',
  );
}
